// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDfuAvailable() {
  return window['go']['backend']['App']['CheckDfuAvailable']();
}

export function CheckDfuStatus() {
  return window['go']['backend']['App']['CheckDfuStatus']();
}

export function FetchPacks() {
  return window['go']['backend']['App']['FetchPacks']();
}

export function FetchReleases() {
  return window['go']['backend']['App']['FetchReleases']();
}

export function FetchTargets(arg1) {
  return window['go']['backend']['App']['FetchTargets'](arg1);
}

export function FlashDfu(arg1) {
  return window['go']['backend']['App']['FlashDfu'](arg1);
}

export function GetVersion() {
  return window['go']['backend']['App']['GetVersion']();
}

export function LoadConfig() {
  return window['go']['backend']['App']['LoadConfig']();
}

export function SaveFirmware(arg1) {
  return window['go']['backend']['App']['SaveFirmware'](arg1);
}

export function SetDarkMode(arg1) {
  return window['go']['backend']['App']['SetDarkMode'](arg1);
}
