// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {config} from '../models';

export function CheckDfuAvailable():Promise<boolean>;

export function CheckDfuStatus():Promise<number>;

export function FetchPacks():Promise<backend.FetchPacksResponse>;

export function FetchReleases():Promise<backend.FetchedReleases>;

export function FetchTargets(arg1:backend.ReleaseMeta):Promise<backend.FetchedTargets>;

export function FlashDfu(arg1:string):Promise<backend.DfuFlashResponse>;

export function GetVersion():Promise<string>;

export function LoadConfig():Promise<config.Config>;

export function SaveFirmware(arg1:string):Promise<backend.SaveFirmwareStatus>;

export function SetDarkMode(arg1:boolean):Promise<void>;
