// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDfuAvailable() {
  return window['go']['backend']['App']['CheckDfuAvailable']();
}

export function CheckDfuStatus() {
  return window['go']['backend']['App']['CheckDfuStatus']();
}

export function CreateLogEntry(arg1, arg2) {
  return window['go']['backend']['App']['CreateLogEntry'](arg1, arg2);
}

export function FetchPacks() {
  return window['go']['backend']['App']['FetchPacks']();
}

export function FetchReleases(arg1) {
  return window['go']['backend']['App']['FetchReleases'](arg1);
}

export function FetchTargets(arg1) {
  return window['go']['backend']['App']['FetchTargets'](arg1);
}

export function FlashDfu(arg1) {
  return window['go']['backend']['App']['FlashDfu'](arg1);
}

export function GetDFULogs() {
  return window['go']['backend']['App']['GetDFULogs']();
}

export function GetLogs() {
  return window['go']['backend']['App']['GetLogs']();
}

export function GetVersion() {
  return window['go']['backend']['App']['GetVersion']();
}

export function LoadConfig() {
  return window['go']['backend']['App']['LoadConfig']();
}

export function SaveFirmware(arg1) {
  return window['go']['backend']['App']['SaveFirmware'](arg1);
}

export function SetDarkMode(arg1) {
  return window['go']['backend']['App']['SetDarkMode'](arg1);
}

export function SetExpertMode(arg1) {
  return window['go']['backend']['App']['SetExpertMode'](arg1);
}
