// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDfuAvailable() {
  return window['go']['main']['App']['CheckDfuAvailable']();
}

export function FetchReleases() {
  return window['go']['main']['App']['FetchReleases']();
}

export function FetchTargets(arg1) {
  return window['go']['main']['App']['FetchTargets'](arg1);
}

export function FlashDfu(arg1) {
  return window['go']['main']['App']['FlashDfu'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
