// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchReleases():Promise<main.FetchedReleases>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;
