// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckDfuAvailable():Promise<boolean>;

export function CheckRadioConnected():Promise<boolean>;

export function FetchReleases():Promise<main.FetchedReleases>;

export function FetchTargets(arg1:main.ReleaseMeta):Promise<main.FetchedTargets>;

export function FlashDfu(arg1:string):Promise<main.DfuFlashResponse>;

export function GetVersion():Promise<string>;

export function SaveFirmware(arg1:string):Promise<main.SaveFirmwareStatus>;
