name: "build"
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-11]
        include:
          - os: windows-latest
            opts: -nsis
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Get Commit Hash
        id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.18"

      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Linux deps
        if: runner.os == 'Linux'
        run: sudo apt-get install libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Install NSIS
        if: runner.os == 'Windows'
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop bucket add extras
          scoop install nsis

      - name: Build with Wails
        run: wails build ${{ matrix.opts }} -ldflags "-X 'main.version=${{ steps.commit.outputs.short }}'"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Uplink-${{ runner.os }}
          path: build/bin/*
