name: "build"
on: [push, pull]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-11]
        include:
          - os: windows-latest
            opts: -nsis
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Get Commit Hash
        id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.18"

      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Linux deps
        if: runner.os == 'Linux'
        run: sudo apt-get install libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Install NSIS
        if: runner.os == 'Windows'
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop bucket add extras
          scoop install nsis

      - name: Build with Wails
        run: wails build ${{ matrix.opts }} -ldflags "-X 'main.version=${{ steps.commit.outputs.short }}'"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: uplink-${{ matrix.os }}
          path: build/bin/*

  upload:
    name: Upload Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: uplink-latest
          path: uplink-latest

      - name: Create dist folder
        run: mkdir dist

      - name: Extract Linux binary
        run: unzip uplink-latest/uplink-ubuntu-20.04.zip -d dist/

      - name: Extract Windows files
        run: unzip uplink-latest/uplink-windows-latest.zip -d dist/

      - name: Move MacOS files
        run: mv uplink-latest/uplink-macos-11.zip dist/

        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Latest Master Build"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: dist/*
          automatic_release_tag: "latest"
          prerelease: false
